
const KEY='eclGrammarProgressV1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
const save=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(e){}};
let progress=read(),activeFilter='all',gameMode='clinic',gameIndex=0,gameScore=0,diagnosticAnswers=[];
const tracks={foundation:'Foundation Repair',time:'Time & Aspect',hypothesis:'Modality & Hypothesis',complex:'Complex Sentence Building',argument:'Argumentation & Nuance',academic:'Academic Precision'};
function pct(list){const done=list.filter(c=>['ready','studied'].includes(progress[c.n])).length;return Math.round(done/list.length*100)}
function updateProgress(){const done=GRAMMAR_CHAPTERS.filter(c=>['ready','studied'].includes(progress[c.n])).length,p=Math.round(done/GRAMMAR_CHAPTERS.length*100);document.documentElement.style.setProperty('--pct',p+'%');document.querySelector('#overallPct').textContent=p+'%';document.querySelector('#overallBar').style.width=p+'%';document.querySelector('#overallText').textContent=`${done} of ${GRAMMAR_CHAPTERS.length} chapters studied or ready to use`;document.querySelectorAll('[data-track-progress]').forEach(el=>{const list=GRAMMAR_CHAPTERS.filter(c=>c.track===el.dataset.trackProgress),v=pct(list);el.style.width=v+'%';el.closest('.track-card').querySelector('.track-percent').textContent=v+'% complete'});}
function renderChapters(){const q=document.querySelector('#search').value.toLowerCase();const grid=document.querySelector('#chapterGrid');grid.innerHTML='';GRAMMAR_CHAPTERS.filter(c=>(activeFilter==='all'||c.track===activeFilter)&&(`${c.n} ${c.title} ${c.desc}`.toLowerCase().includes(q))).forEach(c=>{const card=document.createElement('article');card.className='chapter-card';card.innerHTML=`<span class="num">CHAPTER ${c.n} · ${tracks[c.track]}</span><h3>${c.title}</h3><p>${c.desc||'A focused grammar chapter with explanations, examples, exercises and answers.'}</p><div class="chapter-actions"><a class="btn btn-ghost" href="${c.file}">Open chapter</a><select class="status-select" aria-label="Progress for chapter ${c.n}"><option value="">To study</option><option value="studying">Studying</option><option value="studied">Studied</option><option value="ready">Ready to use</option><option value="revise">Needs revision</option></select></div>`;const s=card.querySelector('select');s.value=progress[c.n]||'';s.onchange=()=>{progress[c.n]=s.value;save(progress);updateProgress()};grid.appendChild(card)});document.querySelector('#resultCount').textContent=`${grid.children.length} chapter${grid.children.length===1?'':'s'}`}
function setFilter(f){activeFilter=f;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderChapters();document.querySelector('#allChapters').scrollIntoView({behavior:'smooth'})}
function recommend(type){const map={basic:'foundation',tenses:'time',complex:'complex',academic:'academic',quick:'all'};setFilter(map[type]||'all');if(type==='lost')openDiagnostic();}
function nextQuestion(){const qs=[...GRAMMAR_QUESTIONS];const q=qs[gameIndex%qs.length];document.querySelector('#gameTitle').textContent=gameMode==='clinic'?'Grammar Clinic':gameMode==='precision'?'Choose the precise form':'Five-minute workout';document.querySelector('#gameQuestion').textContent=q.q;const opts=document.querySelector('#gameOptions');opts.innerHTML='';q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='option';b.textContent=x;b.onclick=()=>answerGame(b,i,q);opts.appendChild(b)});document.querySelector('#gameFeedback').innerHTML='Choose an answer, then read the explanation.';document.querySelector('#gameCounter').textContent=`Question ${gameIndex+1} · Score ${gameScore}`}
function answerGame(btn,i,q){document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(j===q.a)b.classList.add('correct')});if(i!==q.a)btn.classList.add('wrong');else gameScore++;document.querySelector('#gameFeedback').innerHTML=`<strong>${i===q.a?'Correct.':'Not quite.'}</strong> ${q.e} <a href="${GRAMMAR_CHAPTERS.find(c=>c.n===q.c).file}">Review Chapter ${q.c}</a>.`;}
function setGame(mode){gameMode=mode;gameIndex=0;gameScore=0;document.querySelectorAll('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.game===mode));nextQuestion()}
function openDiagnostic(){diagnosticAnswers=[];const m=document.querySelector('#diagnostic');m.classList.remove('hidden');renderDiagnostic(0)}
function renderDiagnostic(i){const qs=GRAMMAR_QUESTIONS.slice(0,12),body=document.querySelector('#diagnosticBody');if(i>=qs.length){const wrong=diagnosticAnswers.filter(x=>!x.ok);const counts={};wrong.forEach(x=>{const t=GRAMMAR_CHAPTERS.find(c=>c.n===x.c).track;counts[t]=(counts[t]||0)+1});const priority=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'academic';body.innerHTML=`<h2>Your diagnostic</h2><p>You answered <strong>${qs.length-wrong.length}/${qs.length}</strong> correctly.</p><div class="result-list"><div class="result-item"><strong>Priority pathway:</strong> ${tracks[priority]}</div>${wrong.slice(0,5).map(x=>`<div class="result-item">Review <a href="${GRAMMAR_CHAPTERS.find(c=>c.n===x.c).file}">Chapter ${x.c}: ${GRAMMAR_CHAPTERS.find(c=>c.n===x.c).title}</a></div>`).join('')}</div><p><button class="btn btn-primary" onclick="closeDiagnostic();setFilter('${priority}')">Show my recommended pathway</button></p>`;return}const q=qs[i];body.innerHTML=`<div class="num">DIAGNOSTIC ${i+1}/${qs.length}</div><h2>${q.q}</h2><div class="options">${q.o.map((o,j)=>`<button class="option" data-i="${j}">${o}</button>`).join('')}</div>`;body.querySelectorAll('.option').forEach(b=>b.onclick=()=>{diagnosticAnswers.push({ok:+b.dataset.i===q.a,c:q.c});renderDiagnostic(i+1)})}
function closeDiagnostic(){document.querySelector('#diagnostic').classList.add('hidden')}
function randomTransfer(){const prompts=['Explain a current social trend using a comparative, a concessive clause and a modal of probability.','Summarise a recent news story using two past tenses and one passive form.','Give a nuanced opinion on AI using hedging, contrast and one conditional sentence.','Present the causes and consequences of a political issue using at least three linking devices.','Contextualise an article using the Present Perfect, then shift to the Past Simple for a dated event.'];document.querySelector('#transferPrompt').textContent=prompts[Math.floor(Math.random()*prompts.length)]}
document.querySelector('#search').addEventListener('input',renderChapters);document.querySelector('#nextGame').onclick=()=>{gameIndex++;nextQuestion()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelectorAll('.game-tab').forEach(b=>b.onclick=()=>setGame(b.dataset.game));document.querySelectorAll('[data-recommend]').forEach(b=>b.onclick=()=>recommend(b.dataset.recommend));document.querySelector('#openDiagnostic').onclick=openDiagnostic;document.querySelector('#closeDiagnostic').onclick=closeDiagnostic;document.querySelector('#newTransfer').onclick=randomTransfer;document.querySelector('#continueBtn').onclick=()=>{const c=GRAMMAR_CHAPTERS.find(c=>progress[c.n]==='studying'||progress[c.n]==='revise')||GRAMMAR_CHAPTERS.find(c=>!progress[c.n]);location.href=c.file};
renderChapters();updateProgress();nextQuestion();randomTransfer();
